### PR TITLE
add checks for MiNLO HJ and HJJ

### PR DESCRIPTION
**Pull request by dsperka**

### CODE REVIEW

**Comment by perrozzi** [comment]
ciao, can you please solve the conflict? very likely is trivial

**Comment by perrozzi** [comment]
thanks. how comes is such a messed up diff?!?!? :-)

**Comment by dsperka** [comment]
I'm not sure, I should have merged your change first. I just want to add these lines:

                  if (strstr(line.c_str(),"Process: HJ")) { // MiNLO HJ
                      std::cout<<iLine<< " "<<line<<std::endl;
                      m_HiggsProdMode = HTXS::GGF;
                      break;
                  }
                  if (strstr(line.c_str(),"Process: HJJ")) { // MiNLO HJJ
                      std::cout<<iLine<< " "<<line<<std::endl;
                      m_HiggsProdMode = HTXS::GGF;
                      break;
                  }

**Comment by perrozzi** [comment]
ok, it seems ok now (I have the feeling that git updates the diff, maybe for conflict fixes it takes a bit to understand what has happened).
thanks

**Pull request merged**
